#!/bin/bash

echo "Running .githooks/pre-commit"

for FILE in $(git diff --cached --name-only)
do
    if [[ $FILE == *.cpp || $FILE == *.h ]]; then
	echo "Running clang-format on $FILE"
	if [[ -e $FILE ]]; then
            clang-format -i $FILE
	    git add $FILE
	fi
    else
	echo "Skipping formatting of $FILE"
    fi
done
