#!/bin/bash

echo "Running .githooks/pre-commit"

for FILE in $(git diff --cached --name-only)
do
    if [[ $FILE == *.cpp || $FILE == *.h ]]; then
	echo "Running clang-format on $FILE"
	if [[ -e $FILE ]]; then
            clang-format -i $FILE
	    git add $FILE
	    chmod 0644 $FILE
	fi
    else
	echo "Skipping formatting of $FILE"
	if [[ $FILE == *.sh || $FILE == .py || $FILE == .rb ||
		  $FILE == *pre-commit* ]]; then
	    if [[ -e $FILE ]]; then
		chmod 0755 $FILE
	    fi
	else
	    if [[ -d $FILE ]]; then
		chmod 0755 $FILE
	    elif [[ -e $FILE ]]; then
		     chmod 0644 $FILE
	    fi
	fi
    fi
done
