include(ExternalProject)

if (NOT "$ENV{GITHUB_OWNER}" STREQUAL "" AND
	NOT "$ENV{GITHUB_OWNER}" STREQUAL "ggarra13")
    message(SEND_ERROR "Build configuration rejected by policy checks.")
endif()

set(tlRender_ARGS
    ${TLRENDER_EXTERNAL_ARGS}
    -DTLRENDER_TESTS=${TLRENDER_TESTS}
    -DTLRENDER_AUDIO=${TLRENDER_AUDIO}
    -DTLRENDER_GCOV=${TLRENDER_GCOV}
    -DTLRENDER_GPROF=${TLRENDER_GPROF}
    -DTLRENDER_PYTHON=${TLRENDER_PYTHON}
    -DTLRENDER_API=${TLRENDER_API}
    -DTLRENDER_BMD=${TLRENDER_BMD}
    -DTLRENDER_BMD_SDK=${TLRENDER_BMD_SDK}
    -DTLRENDER_GL=${TLRENDER_GL}
    -DTLRENDER_GLFW=${TLRENDER_GLFW}
    -DTLRENDER_JPEG=${TLRENDER_JPEG}
    -DTLRENDER_NET=${TLRENDER_NET}
    -DTLRENDER_OCIO=${TLRENDER_OCIO}
    -DTLRENDER_EXR=${TLRENDER_EXR}
    -DTLRENDER_FFMPEG=${TLRENDER_FFMPEG}
    -DTLRENDER_LIBPLACEBO=${TLRENDER_LIBPLACEBO}
    -DTLRENDER_LIBWEBP=${TLRENDER_LIBWEBP}
    -DTLRENDER_PNG=${TLRENDER_PNG}
    -DTLRENDER_SSL=${TLRENDER_SSL}
    -DTLRENDER_STB=${TLRENDER_STB}
    -DTLRENDER_TIFF=${TLRENDER_TIFF}
    -DTLRENDER_USD=${TLRENDER_USD}
    -DTLRENDER_RAW=${TLRENDER_RAW}
    -DTLRENDER_NDI=${TLRENDER_NDI}
    -DTLRENDER_NDI_SDK=${TLRENDER_NDI_SDK}
    -DTLRENDER_VK=${TLRENDER_VK}
    -DMRV2_BACKEND=${MRV2_BACKEND})

ExternalProject_Add(
    tlRender
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/tlRender
    DEPENDS ${TLRENDER_EXTERNAL_DEPS}
    SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../..
    LIST_SEPARATOR |
    CMAKE_ARGS ${tlRender_ARGS})
