include(ExternalProject)

if (USE_SYSTEM_LIBS)
    find_package(AOM CONFIG)
    set(AOM_DEP )
endif()

if (NOT AOM_FOUND)

    set(AOM_GIT_REPOSITORY "https://aomedia.googlesource.com/aom.git")
    set(AOM_GIT_TAG "v3.13.3")  # was v3.13.1

    set(AOM_DEPENDENCIES )

    set(AOM_ARGS ${TLRENDER_EXTERNAL_ARGS})
    list(APPEND AOM_ARGS
	-DCMAKE_INSTALL_LIBDIR=lib
	-DCONFIG_AV1_DECODER=0  # Must not be OFF
	-DCONFIG_PIC=1
	-DENABLE_EXAMPLES=OFF
	-DENABLE_DOCS=OFF
	-DENABLE_TESTDATA=OFF
	-DENABLE_TESTS=OFF
	-DENABLE_TOOLS=OFF
    )
    if(SYSTEM_PROCESSOR_LC MATCHES "^(aarch64|arm64)$")
	list(APPEND AOM_ARGS
	    -DAOM_TARGET_CPU=generic)
    else()
	list(APPEND AOM_ARGS
	    -DCMAKE_ASM_NASM_COMPILER=${CMAKE_INSTALL_PREFIX}/bin/nasm)
	set(AOM_DEPENDENCIES NASM)
    endif()

    message(STATUS "AOM DEPENDENCIES=${AOM_DEPENDENCIES}")

    ExternalProject_Add(
	AOM
	PREFIX ${CMAKE_CURRENT_BINARY_DIR}/../../../deps/AOM

	GIT_REPOSITORY ${AOM_GIT_REPOSITORY}
	GIT_TAG ${AOM_GIT_TAG}

	DEPENDS ${AOM_DEPENDENCIES}

	LIST_SEPARATOR |
	CMAKE_ARGS ${AOM_ARGS}
    )

    set(AOM_DEP AOM)
endif()
