include(ExternalProject)

set(OpenJPH_GIT_REPOSITORY "https://github.com/aous72/OpenJPH.git")
set(OpenJPH_GIT_TAG "0.24.1") # was 0.23.1

set(OpenJPH_DEPENDENCIES ZLIB)
message(STATUS "OpenJPH DEPENDENCIES=${OpenJPH_DEPENDENCIES}")

set(OpenJPH_ARGS
    ${TLRENDER_EXTERNAL_ARGS}
    -D OJPH_ENABLE_TIFF_SUPPORT=OFF
    -D OJPH_BUILD_EXECUTABLES=OFF
)

set(OpenJPH_PATCH )

ExternalProject_Add(
    OpenJPH
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/OpenJPH
    GIT_REPOSITORY ${OpenJPH_GIT_REPOSITORY}
    GIT_TAG ${OpenJPH_GIT_TAG}

    DEPENDS ${OpenJPH_DEPENDENCIES}
    
    PATCH_COMMAND ${OpenJPH_PATCH}
    
    LIST_SEPARATOR |
    CMAKE_ARGS ${OpenJPH_ARGS})

set(OpenJPH_DEP OpenJPH)
