include(ExternalProject)

set(LibWebP_GIT_REPOSITORY "https://github.com/webmproject/libwebp")
set(LibWebP_GIT_TAG "v1.6.0")

set(LibWebP_DEPENDENCIES )
message(STATUS "LibWebP DEPENDENCIES=${LibWebP_DEPENDENCIES}")


set(WEBP_ENABLE_SIMD ON)
if ("$ENV{ARCH}" MATCHES ".*aarch64.*" OR "$ENV{ARCH}" MATCHES ".*arm64.*")
    set(WEBP_ENABLE_SIMD OFF)
endif()


set(LibWebP_PATCH "")

set(LibWebP_ARGS
    ${TLRENDER_EXTERNAL_ARGS}
    -DWEBP_BUILD_ANIM_UTILS=OFF
    -DWEBP_BUILD_CWEBP=OFF
    -DWEBP_BUILD_DWEBP=OFF
    -DWEBP_BUILD_VWEBP=OFF
    -DWEBP_BUILD_GIF2WEBP=OFF
    -DWEBP_BUILD_IMG2WEBP=OFF
    -DWEBP_BUILD_WEBPINFO=OFF
    -DWEBP_BUILD_WEBPMUX=OFF
    -DWEBP_BUILD_EXTRAS=OFF
    -DWEBP_ENABLE_SIMD=${WEBP_ENABLE_SIMD}
)

ExternalProject_Add(
    LibWebP
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/LibWebP
    DEPENDS ${LibWebP_DEPENDENCIES}
    GIT_REPOSITORY ${LibWebP_GIT_REPOSITORY}
    GIT_TAG ${LibWebP_GIT_TAG}
    PATCH_COMMAND ${LibWebP_PATCH}
    LIST_SEPARATOR |
    CMAKE_ARGS ${LibWebP_ARGS})

