include(ExternalProject)

set(PNG_GIT_REPOSITORY "https://github.com/pnggroup/libpng.git")
set(PNG_GIT_TAG "v1.6.44")

set(PNG_DEPENDENCIES ZLIB)
message(STATUS "PNG DEPENDENCIES=${PNG_DEPENDENCIES}")

if(UNIX AND NOT APPLE)
    set(PNG_SHARED_LIBS ON)
    set(PNG_STATIC_LIBS OFF)
else()
    set(PNG_SHARED_LIBS ON)
    set(PNG_STATIC_LIBS OFF)
    if(NOT BUILD_SHARED_LIBS)
	set(PNG_SHARED_LIBS OFF)
	set(PNG_STATIC_LIBS ON)
    endif()
endif()

set(PNG_PATCH ${CMAKE_COMMAND} -E copy_if_different
    ${CMAKE_CURRENT_SOURCE_DIR}/patches/PNG-patch/scripts/pnglibconf.h.prebuilt
    ${CMAKE_CURRENT_BINARY_DIR}/PNG/src/PNG/scripts/)

set(PNG_ARGS
    ${TLRENDER_EXTERNAL_ARGS}
    -DCMAKE_INSTALL_LIBDIR=lib
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON
    -DPNG_SHARED=${PNG_SHARED_LIBS}
    -DPNG_STATIC=${PNG_STATIC_LIBS}
    -DPNG_TESTS=OFF
    -DPNG_ARM_NEON=off   # must be lower-case
    -DSKIP_INSTALL_EXECUTABLES=ON
    -DSKIP_INSTALL_PROGRAMS=ON
    -DSKIP_INSTALL_FILES=ON)

ExternalProject_Add(
    PNG
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/PNG
    DEPENDS ${PNG_DEPENDENCIES}
    GIT_REPOSITORY ${PNG_GIT_REPOSITORY}
    GIT_TAG ${PNG_GIT_TAG}

    PATCH_COMMAND ${PNG_PATCH}

    LIST_SEPARATOR |
    CMAKE_ARGS ${PNG_ARGS})
