#!/bin/bash


export TLRENDER_QT6=ON
export TLRENDER_QT5=OFF

. build_dir.sh

cd $BUILD_DIR

cmake ../../.. -G Ninja -D CMAKE_VERBOSE_MAKEFILE=ON -D CMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -D CMAKE_INSTALL_PREFIX=$PWD/install -D CMAKE_PREFIX_PATH=$PWD/install -D TLRENDER_PROGRAMS=ON -D TLRENDER_EXAMPLES=FALSE -D TLRENDER_TESTS=FALSE -D TLRENDER_QT6=${TLRENDER_QT6} -D TLRENDER_QT5=${TLRENDER_QT5} -D LIBINTL_ROOT=${LIBINTL_ROOT} -D BUILD_FLTK=OFF -D BUILD_BOOST=OFF -D BUILD_MRVIEWER=OFF

cmake --build . $FLAGS --config $CMAKE_BUILD_TYPE

cd -

. qt_end.sh
