// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by svg_to_cpp.py from 'CompareWipe.svg'

#pragma once

#include <cstddef> // For size_t

// Extern declaration for the SVG data array
extern const unsigned char CompareWipe_svg[];

// Extern declaration for the size of the SVG data
extern const size_t CompareWipe_svg_size;
