// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by svg_to_cpp.py from 'Compare.svg'

#pragma once

#include <cstddef> // For size_t

// Extern declaration for the SVG data array
extern const unsigned char Compare_svg[];

// Extern declaration for the size of the SVG data
extern const size_t Compare_svg_size;
