// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by svg_to_cpp.py from 'FileCloseAll.svg'

#pragma once

#include <cstddef> // For size_t

// Extern declaration for the SVG data array
extern const unsigned char FileCloseAll_svg[];

// Extern declaration for the size of the SVG data
extern const size_t FileCloseAll_svg_size;
