// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by svg_to_cpp.py from 'OutlineRectangle.svg'

#pragma once

#include <cstddef> // For size_t

// Extern declaration for the SVG data array
extern const unsigned char OutlineRectangle_svg[];

// Extern declaration for the size of the SVG data
extern const size_t OutlineRectangle_svg_size;
