// AUTO-GENERATED FILE - DO NOT EDIT!
// Generated by svg_to_cpp.py from 'Trashcan.svg'

#pragma once

#include <cstddef> // For size_t

// Extern declaration for the SVG data array
extern const unsigned char Trashcan_svg[];

// Extern declaration for the size of the SVG data
extern const size_t Trashcan_svg_size;
