# SPDX-License-Identifier: BSD-3-Clause
# mrv2 
# Copyright Contributors to the mrv2 Project. All rights reserved.

include( ExternalProject )


message(STATUS "PREVIOUS Build pybind11 PYTHON_EXECUTABLE=${Python_EXECUTABLE}")
message(STATUS "PREVIOUS Build pybind11 Python_VERSION=${Python_VERSION}")
message(STATUS "PREVIOUS Build pybind11 PYTHON_VERSION=${PYTHON_VERSION}")

ExternalProject_Add(
    pybind11
    GIT_REPOSITORY "https://github.com/pybind/pybind11"
    GIT_TAG v2.10.3
    GIT_PROGRESS 1
    DEPENDS ${PYTHON_DEP}
    CMAKE_ARGS
    -DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHIECTURES}
    -DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}
    -DCMAKE_VERBOSE_MAKEFILE=${CMAKE_VERBOSE_MAKEFILE}
    -DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
    -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
    -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
    -DPYBIND11_TEST:BOOL=OFF
)

message(STATUS "AFTER Build pybind11 PYTHON_EXECUTABLE=${PYTHON_EXECUTABLE}")
message(STATUS "AFTER Build pybind11 Python_VERSION=${Python_VERSION}")
message(STATUS "AFTER Build pybind11 PYTHON_VERSION=${PYTHON_VERSION}")
    
set( PYBIND11_DEP pybind11 )
