# SPDX-License-Identifier: BSD-3-Clause
# mrv2 
# Copyright Contributors to the mrv2 Project. All rights reserved.

include( ExternalProject )

# Stable TAG
set( POCO_REPOSITORY "https://github.com/pocoproject/poco.git" )
set( POCO_GIT_TAG poco-1.14.1-release )


set(POCO_DEPENDENCIES )

set(POCO_OPENSSL OFF)
if (TLRENDER_NET)
    set(POCO_OPENSSL ON)
    list(APPEND POCO_DEPENDENCIES ${OpenSSL_DEP})
endif()

set(POCO_SHARED_LIBS OFF)
if(WIN32)
    set(POCO_SHARED_LIBS ON)
endif()

message(STATUS "POCO DEPENDENCIES=${POCO_DEPENDENCIES}")


ExternalProject_Add(
    POCO
    GIT_REPOSITORY ${POCO_REPOSITORY}
    GIT_TAG ${POCO_GIT_TAG}
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/deps/POCO
    GIT_PROGRESS 1
    GIT_SHALLOW 1

    DEPENDS ${POCO_DEPENDENCIES}

    LIST_SEPARATOR |
    
    PATCH_COMMAND ${POCO_PATCH}
    CMAKE_ARGS
    -DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHIECTURES}
    -DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}
    -DCMAKE_VERBOSE_MAKEFILE=${CMAKE_VERBOSE_MAKEFILE}
    -DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH_TMP}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH_TMP}
    -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
    -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
    -DCMAKE_INSTALL_MESSAGE=${CMAKE_INSTALL_MESSAGE}
    -DCMAKE_RELEASE_POSTFIX=""
    -DENABLE_FOUNDATION=ON
    -DENABLE_NET=ON
    -DENABLE_NETSSL=${POCO_OPENSSL}  # We will use this
    -DENABLE_CRYPTO=${POCO_OPENSSL}  # We might use this
    -DBUILD_SHARED_LIBS=${POCO_SHARED_LIBS}
    -DENABLE_XML=${POCO_OPENSSL}    # We need this with NetSSL
    -DENABLE_JSON=${POCO_OPENSSL}   # We need this with NetSSL
    -DENABLE_JWT=OFF
    -DENABLE_DATA=OFF
    -DENABLE_ACTIVERECORD=OFF
    -DENABLE_ACTIVERECORD_COMPILER=OFF
    -DENABLE_DATA=OFF
    -DENABLE_DATA_SQLITE=OFF
    -DENABLE_DATA_MYSQL=OFF
    -DENABLE_DATA_POSTGRESQL=OFF
    -DENABLE_DATA_ODBC=OFF
    -DENABLE_MONGODB=OFF
    -DENABLE_REDIS=OFF
    -DENABLE_PDF=OFF
    -DENABLE_UTIL=OFF
    -DENABLE_ZIP=OFF
    -DENABLE_SEVENZIP=OFF
    -DENABLE_APACHECONNECTOR=OFF
    -DENABLE_CPPPARSER=OFF
    -DENABLE_ENCODINGS=OFF
    -DENABLE_PAGECOMPILER=OFF
    -DENABLE_PAGECOMPILER_FILE2PAGE=OFF
    -DENABLE_POCODOC=OFF
    -DENABLE_PROMETHEUS=OFF
    -DENABLE_TESTS=OFF
    -DPOCO_UNBUNDLED=OFF    
)

set( POCO_DEP POCO )
