# SPDX-License-Identifier: BSD-3-Clause
# mrv2 
# Copyright Contributors to the mrv2 Project. All rights reserved.

include( ExternalProject )

set(cpptrace_REPOSITORY "https://github.com/jeremy-rifkin/cpptrace.git")
set(cpptrace_TAG v1.0.4)
#set(cpptrace_TAG c37b5ed7364f4fc1c58e92d13399cd04656e6572)

ExternalProject_Add(
    cpptrace
    GIT_REPOSITORY ${cpptrace_REPOSITORY}
    GIT_TAG ${cpptrace_TAG}
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/deps/cpptrace

    LIST_SEPARATOR |
    
    CMAKE_ARGS 
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
    -DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHIECTURES}
    -DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}
    -DCMAKE_VERBOSE_MAKEFILE=${CMAKE_VERBOSE_MAKEFILE}
    -DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH_TMP}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH_TMP}
    -DCMAKE_INSTALL_MESSAGE=${CMAKE_INSTALL_MESSAGE}
)

set( cpptrace_DEP cpptrace )
