set( CMAKE_CXX_STANDARD 14 )
set( CMAKE_CXX_STANDARD_REQUIRED ON )
set( CMAKE_CXX_EXTENSIONS OFF )



set(BUILD_FLTK TRUE CACHE BOOL "Enable FLTK building")
set(BUILD_BOOST TRUE CACHE BOOL "Enable Boost building")
set(BUILD_MRVIEWER TRUE CACHE BOOL "Enable mrViewer2 (mrv2) building")
