name: Win64 Vulkan

on:
  push:
    branches-ignore:
      - main
      - beta
      
jobs:
  ###################################
  #                                 #
  # FULL BUILDS                     #
  #                                 #
  ###################################
  windows-vulkan-full-build:
    runs-on: windows-2022

    defaults:
      run:
        shell: msys2 {0}

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Visual C++ Redistributable 2022
      run: |
        $vc_redist_url_2022 = "https://aka.ms/vs/17/release/vc_redist.x64.exe"
        Invoke-WebRequest -Uri $vc_redist_url_2022 -OutFile vc_redist_2022.x64.exe
        Start-Process vc_redist_2022.x64.exe -ArgumentList "/install", "/quiet", "/norestart" -Wait
      shell: powershell
      
    - name: Install Vulkan SDK
      # This action automatically downloads and installs the Vulkan SDK
      # There are several community actions available, 'jakoch/install-vulkan-sdk-action' is a good option.
      # You can specify a version or let it default to the latest.
      uses: jakoch/install-vulkan-sdk-action@v1
      with:
        # vulkan_version: 1.3.283.0 # Specify a stable Vulkan SDK version
        # optional_components: com.lunarg.vulkan.vma # Example: install Vulkan Memory Allocator
        install_runtime: true
        cache: true
        stripdown: true # Reduce cache size
        
    - name: Synchronize clock
      shell: cmd
      run: |
        w32tm /config /manualpeerlist:time.windows.com /syncfromflags:manual /reliable:YES /update
        net stop w32time
        net start w32time
        w32tm /resync /rediscover
          
    - name: Setup MSYS
      uses: msys2/setup-msys2@v2
      with:
        update: true
        path-type: inherit
        
    - name: Get machine name
      run: |
        echo "Machine name: $RUNNER_NAME"
    
    # Install Vulkan SDK
    # - name: Install Vulkan SDK
    #   if: github.ref_name == 'vulkan'
    #   run: |

    #     . ./etc/windows/install_vulkan.sh
        
    #     # Persist environment variables for subsequent steps
    #     echo "VULKAN_SDK=$VULKAN_SDK" >> $GITHUB_ENV
    #     echo "VK_LAYER_PATH=$VK_LAYER_PATH" >> $GITHUB_ENV
    #     echo "${VULKAN_SDK}/bin" >> $GITHUB_PATH

    # Verify Vulkan installation (does not work on Github Actions)
    # - name: Verify Vulkan
    #   run: |
    #     vulkaninfo --summary

    - name: Setup environment
      run: mkdir -p ssh
      
    - name: Decode SSH key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ssh/id_rsa
      shell: bash
        
    - name: Decode FLTK SSH key
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.FLTK_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
    - name: Set permissions on SSH key
      shell: cmd
      run: |
        icacls "ssh\id_rsa" /inheritance:r /grant:r "%USERNAME%:R"
        
    - name: Add SourceForge to known_hosts
      shell: bash
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts
      
    - name: Set executable permissions
      run: |
        chmod +x ./*.sh ./bin/*.sh ./etc/*.sh ./bin/release/*.sh
        
    # - name: Install cmake
    #   run: |
    #     ./etc/install_cmake.sh
        
    - name: Install MSYS2 Dependencies
      run: |
        pacman -S --noconfirm nasm rsync
      
    - name: Build mrv2
      run: |
        ./etc/runme_nolog.sh -v -t package -D TLRENDER_USD=OFF -vk
        
    - name: Upload binaries  # Conditional step (beta branch only)
      if: github.ref_name == 'vulkan'
      run: |
        ./bin/release/upload_sourceforge.sh -vk
