name: Vulkan MacOS Intel

on:
  push:
    branches-ignore:
      - main
      - beta

jobs:
  ###################################
  #                                 #
  # FULL BUILDS                     #
  #                                 #
  ###################################
  macos-13-vulkan-full-build:
    runs-on: macos-13

    steps:
    
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Get machine name
      run: |
        echo "Machine name: $RUNNER_NAME"

    - name: Install ninja-build
      run: brew install ninja
      
    - name: Install automake
      run: brew install automake curl rsync

    - name: Install GNU sed
      run: brew install gnu-sed
      
    - name: Install Python dependencies
      run: brew install libb2 libffi readline sqlite3 xz zlib
        
    - name: Install pyFLTK dependencies
      run: brew install swig
        
    # Download and install Vulkan SDK with MoltenVK
    - name: Install Vulkan SDK
      run: |
        brew install vulkan-loader
        brew install molten-vk
        brew install vulkan-tools
        brew install shaderc
        brew install glslang
        brew install vulkan-profiles
        brew install spirv-tools

    # Verify Vulkan installation
    - name: Verify Vulkan
      run: |
        export VK_LAYER_DEBUG=all
        vulkaninfo --summary
        
    - name: Setup environment
      run: mkdir -p ssh

    - name: Decode SSH key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ssh/id_rsa
      shell: bash
  
    - name: Set permissions on SSH key
      run: chmod 600 ssh/id_rsa

    - name: Decode FLTK SSH key
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.FLTK_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      
    - name: Add SourceForge to known_hosts
      run: ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts

    - name: Set executable permissions
      run: |
        chmod +x ./*.sh ./bin/*.sh ./etc/*.sh ./bin/release/*.sh

    - name: List disk space
      run: |
        df -k
        
    - name: Build mrv2
      run: |
        ./etc/runme_nolog.sh -D TLRENDER_USD=OFF -t package -vk
      
    - name: Upload binaries
      run: |
        ./bin/release/upload_sourceforge.sh -vk
